### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by samjett247** [stev-ou/stev#4]

**Comment by samjett247** [comment]
- [ ] Change the x-axis for any courses and figures to show only subject code and number (ame3353) and then the full name only showing in the tooltip (ame3353: .... )

**Comment by samjett247** [comment]
- [ ] Add a tag for class size (small (<20, typically), medium (<50, typically) , large(>50, typically)) to the course page. Although, this will be a whole-class evaluation, not specific to sections . Not sure, thinking about it

**Comment by schuermannator** [comment]
- [ ] Header search
- [ ] DNS/SSL
- [ ] Analytics
- [ ] idk

**Comment by samjett247** [comment]
- [ ] Add "About" Page and some way to navigate there
         - If anyone wants this, you got it : )

**Comment by schuermannator** [comment]
Font size inconsistent (esp. on the graph with prof names in the legend)

**Comment by schuermannator** [comment]
migrating
